/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.settings.ActionSettings;
import gui.settings.ButtonSettings;
import gui.settings.IRegulator;
import gui.settings.IconSettings;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;

/**
 *
 * @author User
 */
public class HesabEkrani extends javax.swing.JFrame implements IRegulator{

    /**
     * Creates new form HesabEkrani
     */
    public HesabEkrani() {
        initComponents();
        getEdits();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hesabEkranPaneli = new javax.swing.JPanel();
        xosgeldinLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        dollarIcon = new javax.swing.JLabel();
        miqdarLabel = new javax.swing.JLabel();
        pulCekIcon = new javax.swing.JLabel();
        pulcekButton = new javax.swing.JButton();
        pulkocurIcon = new javax.swing.JLabel();
        pulkocurButon = new javax.swing.JButton();
        kocurmeIcon = new javax.swing.JLabel();
        odemelerIcon = new javax.swing.JLabel();
        kocurmeButton = new javax.swing.JButton();
        odemelerButton = new javax.swing.JButton();
        settingsLabel = new javax.swing.JLabel();
        logoutLabel1 = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sizin Hesab Ekraniniz");

        hesabEkranPaneli.setBackground(new java.awt.Color(0, 153, 153));

        xosgeldinLabel.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
        xosgeldinLabel.setText("Welcome");

        usernameLabel.setFont(new java.awt.Font("Niagara Engraved", 0, 48)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 51, 51));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Username");

        dollarIcon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dollarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Icons/dollarIcon.png"))); // NOI18N

        miqdarLabel.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        miqdarLabel.setText("[ Miqdar ]");

        pulCekIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Icons/withdrawIcon.png"))); // NOI18N
        pulCekIcon.setToolTipText("");

        pulcekButton.setBackground(new java.awt.Color(0, 153, 102));
        pulcekButton.setText("Pul Cek");
        pulcekButton.setToolTipText("Pul Cek");
        pulcekButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pulcekButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pulcekButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pulcekButtonMouseExited(evt);
            }
        });
        pulcekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulcekButtonActionPerformed(evt);
            }
        });

        pulkocurIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Icons/depositIcon.png"))); // NOI18N

        pulkocurButon.setBackground(new java.awt.Color(255, 204, 204));
        pulkocurButon.setText("Pul Kocur");
        pulkocurButon.setToolTipText("Pul Kocur");
        pulkocurButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pulkocurButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pulkocurButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pulkocurButonMouseExited(evt);
            }
        });
        pulkocurButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulkocurButonActionPerformed(evt);
            }
        });

        kocurmeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Icons/transferIcon.png"))); // NOI18N

        odemelerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Icons/paymentIcon.png"))); // NOI18N

        kocurmeButton.setBackground(new java.awt.Color(255, 153, 0));
        kocurmeButton.setText("Gonder");
        kocurmeButton.setToolTipText("Gonder");
        kocurmeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kocurmeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kocurmeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kocurmeButtonMouseExited(evt);
            }
        });
        kocurmeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kocurmeButtonActionPerformed(evt);
            }
        });

        odemelerButton.setBackground(new java.awt.Color(255, 153, 153));
        odemelerButton.setText("Odemeler");
        odemelerButton.setToolTipText("Odemeler");
        odemelerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        odemelerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                odemelerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                odemelerButtonMouseExited(evt);
            }
        });
        odemelerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odemelerButtonActionPerformed(evt);
            }
        });

        settingsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Icons/settingsIcon.png"))); // NOI18N
        settingsLabel.setToolTipText("Settings");
        settingsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsLabelMouseClicked(evt);
            }
        });

        logoutLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Icons/logoutIcon.png"))); // NOI18N
        logoutLabel1.setToolTipText("LogOut");
        logoutLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabel1MouseClicked(evt);
            }
        });

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Icons/icons8_user_50px.png"))); // NOI18N

        javax.swing.GroupLayout hesabEkranPaneliLayout = new javax.swing.GroupLayout(hesabEkranPaneli);
        hesabEkranPaneli.setLayout(hesabEkranPaneliLayout);
        hesabEkranPaneliLayout.setHorizontalGroup(
            hesabEkranPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hesabEkranPaneliLayout.createSequentialGroup()
                .addComponent(logoutLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(settingsLabel))
            .addGroup(hesabEkranPaneliLayout.createSequentialGroup()
                .addGroup(hesabEkranPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(hesabEkranPaneliLayout.createSequentialGroup()
                        .addGroup(hesabEkranPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(pulcekButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pulCekIcon))
                        .addGap(18, 18, 18)
                        .addGroup(hesabEkranPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(pulkocurButon)
                            .addComponent(pulkocurIcon))
                        .addGap(40, 40, 40)
                        .addGroup(hesabEkranPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(kocurmeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kocurmeIcon))
                        .addGap(40, 40, 40)
                        .addGroup(hesabEkranPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(odemelerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(odemelerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(hesabEkranPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(hesabEkranPaneliLayout.createSequentialGroup()
                            .addGap(149, 149, 149)
                            .addComponent(dollarIcon)
                            .addGap(40, 40, 40)
                            .addComponent(miqdarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(hesabEkranPaneliLayout.createSequentialGroup()
                            .addGap(235, 235, 235)
                            .addComponent(xosgeldinLabel)))
                    .addGroup(hesabEkranPaneliLayout.createSequentialGroup()
                        .addComponent(userIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        hesabEkranPaneliLayout.setVerticalGroup(
            hesabEkranPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hesabEkranPaneliLayout.createSequentialGroup()
                .addGroup(hesabEkranPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xosgeldinLabel)
                .addGap(18, 18, 18)
                .addGroup(hesabEkranPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIcon))
                .addGap(13, 13, 13)
                .addGroup(hesabEkranPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hesabEkranPaneliLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(miqdarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hesabEkranPaneliLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(dollarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(hesabEkranPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(hesabEkranPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(hesabEkranPaneliLayout.createSequentialGroup()
                            .addComponent(pulCekIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pulcekButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(hesabEkranPaneliLayout.createSequentialGroup()
                            .addComponent(pulkocurIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pulkocurButon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(hesabEkranPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(hesabEkranPaneliLayout.createSequentialGroup()
                            .addComponent(kocurmeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(kocurmeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(hesabEkranPaneliLayout.createSequentialGroup()
                            .addComponent(odemelerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(odemelerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hesabEkranPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hesabEkranPaneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void getEdits() {
        setLocationRelativeTo(null);
        hesabEkranPaneli.setFocusable(true);
    }
    
    /*
    button renglendirmeleri ve icon deyisimleri
    */
    private void setBgFg(Component c){
        ButtonSettings.setBgFg( (JButton)c, Color.BLACK, Color.BLACK);
    }
    private void pulcekButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pulcekButtonMouseEntered
        this.setBgFg(evt.getComponent());
        IconSettings.changeIcon(pulCekIcon, "withdrawIcon2");
    }//GEN-LAST:event_pulcekButtonMouseEntered

    private void pulcekButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pulcekButtonMouseExited
        ButtonSettings.setOriginalBgFg((JButton)evt.getComponent());
        IconSettings.setOriginalIcon(pulCekIcon);
    }//GEN-LAST:event_pulcekButtonMouseExited

    private void pulkocurButonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pulkocurButonMouseEntered
        this.setBgFg(evt.getComponent());
        IconSettings.changeIcon(pulkocurIcon, "depositIcon2");
    }//GEN-LAST:event_pulkocurButonMouseEntered

    private void pulkocurButonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pulkocurButonMouseExited
        ButtonSettings.setOriginalBgFg((JButton)evt.getComponent());
        IconSettings.setOriginalIcon(pulkocurIcon);
    }//GEN-LAST:event_pulkocurButonMouseExited

    private void kocurmeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kocurmeButtonMouseEntered
        this.setBgFg(evt.getComponent());
        IconSettings.changeIcon(kocurmeIcon, "transferIcon2");
    }//GEN-LAST:event_kocurmeButtonMouseEntered

    private void kocurmeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kocurmeButtonMouseExited
        ButtonSettings.setOriginalBgFg((JButton)evt.getComponent());
        IconSettings.setOriginalIcon(kocurmeIcon);
    }//GEN-LAST:event_kocurmeButtonMouseExited

    private void odemelerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odemelerButtonMouseEntered
        this.setBgFg(evt.getComponent());
        IconSettings.changeIcon(odemelerIcon, "paymentIcon2");
    }//GEN-LAST:event_odemelerButtonMouseEntered

    private void odemelerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odemelerButtonMouseExited
        ButtonSettings.setOriginalBgFg((JButton)evt.getComponent());
        IconSettings.setOriginalIcon(odemelerIcon);
    }//GEN-LAST:event_odemelerButtonMouseExited

    /*
    *Action lar
    */
    private void pulcekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulcekButtonActionPerformed
        ActionSettings.setVisible(this, new PulCekEkrani());
    }//GEN-LAST:event_pulcekButtonActionPerformed

    private void pulkocurButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulkocurButonActionPerformed
        ActionSettings.setVisible(this, new PulKocurEkrani());
    }//GEN-LAST:event_pulkocurButonActionPerformed

    private void kocurmeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kocurmeButtonActionPerformed
        ActionSettings.setVisible(this, new GonderEkrani());
    }//GEN-LAST:event_kocurmeButtonActionPerformed

    private void odemelerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odemelerButtonActionPerformed
        ActionSettings.setVisible(this, new OdemeEkrani());
    }//GEN-LAST:event_odemelerButtonActionPerformed

    private void logoutLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabel1MouseClicked
        ActionSettings.setVisible(this, new GirisEkran());
    }//GEN-LAST:event_logoutLabel1MouseClicked

    private void settingsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsLabelMouseClicked
        ActionSettings.setVisible(this, new SettingsEkrani());
    }//GEN-LAST:event_settingsLabelMouseClicked

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HesabEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HesabEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HesabEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HesabEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HesabEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dollarIcon;
    private javax.swing.JPanel hesabEkranPaneli;
    private javax.swing.JButton kocurmeButton;
    private javax.swing.JLabel kocurmeIcon;
    private javax.swing.JLabel logoutLabel1;
    private javax.swing.JLabel miqdarLabel;
    private javax.swing.JButton odemelerButton;
    private javax.swing.JLabel odemelerIcon;
    private javax.swing.JLabel pulCekIcon;
    private javax.swing.JButton pulcekButton;
    private javax.swing.JButton pulkocurButon;
    private javax.swing.JLabel pulkocurIcon;
    private javax.swing.JLabel settingsLabel;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel xosgeldinLabel;
    // End of variables declaration//GEN-END:variables
}
